name: Azure Run scaffold application test in week-3 folder 
on: 
  push:
    paths:
        - 'Week-3/scaffold/**'
jobs:
  build:
    defaults:
      run:
        working-directory: Week-3/scaffold
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.13
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.13
    - name: Install dependencies
      run: |
        make install-azure
    - name: Lint with Pylint
      run: |
        make lint
    - name: Test with Pytest
      run: |
        make test

